# Project-wide Gradle settings.

org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.java.home=/Applications/Android Studio.app/Contents/jbr/Contents/Home


# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official

# ===== KAPT FIX (AGP 8.x) =====
kapt.use.worker.api=false
kapt.incremental.apt=true
